version: 0.2

env:
  variables:
    BUCKET: boazz-packages

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.8
    commands:
      - pip install --upgrade awscli aws-sam-cli
      - sam --version
  build:
    commands:
      - sam build
      - sam package --s3-bucket $BUCKET --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - packaged.yaml
